### PR TITLE
Added coverage for missing SponsorId field in config test

### PR DESCRIPTION
**Pull request by mirokuratczyk**
Added coverage for missing SponsorId field in config test Test_LoadConfig_BadJson

### CODE REVIEW

**Comment by adam-p** [comment]
Thanks for this. A couple of things with it:

### The test

`suite.requiredFields` is derived from the contents of the README. The second element it might not always be `SponsorId`, and it might not even always have two elements. (Of course, it might not even have one, but anyway.) 

So, how about... Can you replace your test and the one above it with a loop that tests all of the `suite.requiredFields`? That will reduce the chance of the test breaking, reduce the chance of a comment mismatch, and maximize the coverage (for the required fields).

### CLA

When talking about merging your PR, we realized that we're long overdue for adding a Contributor License Agreement. So we added one. Can you "sign" it and include in your PR? There are instructions in [CONTRIBUTING.md](https://github.com/Psiphon-Labs/psiphon-tunnel-core/blob/master/CONTRIBUTING.md). (Let us know if the instructions are crap/imcomplete.)

Thanks.

**Comment by mirokuratczyk** [comment]
Thanks for the quick response. I have made the aforementioned changes.

**Comment by adam-p** [comment]
Thanks, Miro.

A small-ish suggestion... I/we would have preferred that the code look something like this:

```go
	// Test config missing each required field
	// **** In the iterator, use the array item (string) instead of the index
	for _, field := range suite.requiredFields { 
	  json.Unmarshal(suite.confStubBlob, &testObj)
	  delete(testObj, field)
	  testObjJSON, _ = json.Marshal(testObj)
	  _, err = LoadConfig(testObjJSON)
	  // **** Show which field failed. (I have no idea if NotNil will format, but anyway.)
	  suite.NotNil(err, "JSON with one of our required fields missing should fail: %s", field)
	}
```

...but we're not going to require it.

**Comment by mirokuratczyk** [comment]
Very good point. NotNil will format as you have shown, I have made this change in pull request #164. In addition, now all fields are looped over for each surrounding test case.

**Pull request merged**
